
spring:
   datasource:
    name: garage
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3307/prm?useUnicode=true&characterEncoding=utf8
    username: prm
    password: prm
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

#logging:
#  level: debug

