server:
  context-path: /prm
  port: 8080

spring:
  profiles:
    active: local
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
    static-path-pattern: /**
#  resources:
#    static-locations: component/**,css/**,images/**,js/**

logging:
  level:
    com.wangyu.mapper: debug

