spring:
   datasource:
    name: garage
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.107.85.17:3306/garage?useUnicode=true&characterEncoding=utf8
    username: garage
    password: 123456
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20


logging:
  level: info

